image: python:3.10

cache:
  paths:
    - __pypackages__

before_script:
  - python --version  # For debugging
  - mkdir __pypackages__ -p  # Ensures folder is used by pdm, speeding up install step
  - python -m pip install pdm
  - pdm install --dev

run_pytests:
  stage: test
  image: python:latest
  script:
    # Run unit tests
    - pdm run coverage run --source=pydantify -m pytest tests -v
    - pdm run coverage report -m --precision=2 --omit="*/run.py"
    - pdm run coverage xml --omit="*/run.py"
    - pdm run coverage html --omit="*/run.py"
  coverage: '/TOTAL.+?(\d+.\d+\%)/'
  artifacts:
      paths:
          - coverage.xml
          - htmlcov/
      reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml

pages:
  stage: deploy
  dependencies:
    - run_pytests
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  # only:
  #   - master
