[project]
name = "yang2pydantic"
version = "0.1.0"
description = "Makes network automation pydantic."
authors = [
    {name = "Dominic Walther", email = "dominic.walther@ost.ch"},
    {name = "Dejan Jovicic", email = "dejan.jovicic@ost.ch"},
]
dependencies = [
    "pydantic>=1.10.2",
]
requires-python = ">=3.10"
readme = "README.md"

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]

[project.scripts]
run-my-project = "yang2pydantic.main:start"

[project.urls]
Repository = "https://gitlab.ost.ch/pydantic-sa/yang2pydantic"

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
