[project]
name = "pydantify"
version = "0.1.0"
description = "Makes network automation pydantic."
authors = [
    { name = "Dominic Walther", email = "dominic.walther@ost.ch" },
    { name = "Dejan Jovicic", email = "dejan.jovicic@ost.ch" },
]
dependencies = [
    "pydantic>=1.10.2",
    "requests>=2.28.1",
    "datamodel-code-generator>=0.13.1",
    "genson>=1.2.2",
    "pyang>=2.5.3",
]
requires-python = ">=3.10"
readme = "README.md"

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]

[project.scripts]
pydantify = "pydantify.main:main"

[project.urls]
Repository = "https://gitlab.ost.ch/pydantic-sa/yang2pydantic"

[project.optional-dependencies]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "autopep8>=1.7.0",
    "black>=22.10.0",
]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
